name: CI/CD | Terraform + Docker + App | AWS VPC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  

jobs:

  job_01:
    name: GitHub Checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    
  job_02:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    needs: job_01
    steps:
    - uses: actions/checkout@v3
    
    
  job_03:
    name: Build the Docker image
    runs-on: ubuntu-latest
    needs: job_02
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
  job_04:
    name: Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: job_03
    steps:
    - uses: actions/checkout@v3
    
  job_05:
    name: Run Docker Image on EC2 Instance
    runs-on: ubuntu-latest
    needs: job_04
    steps:
    - uses: actions/checkout@v3


    
